### ISSUE TITLE
Default data is not set correctly

### ISSUE THREAD

**Issue by JPry** [imath/wp-statuses#13]
When registering a custom post status with this plugin active, I expected the following default values:

```php
array(
    'show_in_metabox_dropdown' => true,
    'show_in_inline_dropdown'  => true,
    'post_type'                => array( /* all registered post types */ ),
);
```

Instead, these parameters aren't set at all if I don't explicitly pass them.

This looks to be an error in the conditional that checks for `$status_data` at line 158 of`class-wp-statuses-core-status.php`.

**Comment by imath** [comment]
Hi @JPry 

Thanks a lot for your feedback. I'll look at it this weekend.
