### ISSUE TITLE
Missing Composer file

### ISSUE THREAD

**Issue by AdamQuadmon** [imath/wp-statuses#17]
Hi there, thanks for your work!

Can you please add a composer file to this repo?
I'm using Bedrock and I'd like to use your plugin in my workflow.

**Comment by imath** [comment]
Hi!

Thanks for your interest about this plugin. What about pulling a request about it ? I’d be happy to commit it ;)

imath.
http://profiles.wordpress.org/imath/

**Comment by AdamQuadmon** [comment]
here it is

https://github.com/imath/wp-statuses/pull/18

**Comment by imath** [comment]
Fixed ! Thanks @AdamQuadmon
