### ISSUE TITLE
Change order of statuses in metabox

### ISSUE THREAD

**Issue by seshatasensi** [imath/wp-statuses#23]
Hey, great work on this plugin, it's exactly what I was looking for. Now I need to change the order of the statuses in the metabox, but I'm not sure how to achieve this. Specifically, I need to move the custom statuses above the default wordpress statuses. If you can advise me I'd be very grateful!

**Comment by imath** [comment]
Thanks for your feedback, I think you’ll need a filter I was planning to introduce in next release. I’ll check about it, will confirm & explain how to do it soon.
