### ISSUE TITLE
future post status throws metabox errors (1.2.4)

### ISSUE THREAD

**Issue by lajala** [imath/wp-statuses#24]
Posts which are scheduled for future publication throw the following pair of errors in the metabox:

> Notice: Undefined index: future in [wp-statuses/inc/admin/classes/class-wp-statuses-admin.php](https://github.com/imath/wp-statuses/blob/1.2.4/inc/admin/classes/class-wp-statuses-admin.php) on line 546

> Notice: Undefined index: future in [wp-statuses/inc/admin/classes/class-wp-statuses-admin.php](https://github.com/imath/wp-statuses/blob/1.2.4/inc/admin/classes/class-wp-statuses-admin.php) on line 630

Both errors seem to be related: `future` is one of the standard WordPress post statuses, but it appears that the plugin is searching for it within the array of custom statuses. Any recommendations on how to rectify these errors?

**Comment by lajala** [comment]
On closer review, it looks like Pull Request #22 has addressed this issue and the minor version of the plugin should be bumped from 1.2.4 to 1.2.5.

**Comment by imath** [comment]
Hi !

Thanks for the reminder. 1.2.5 is now available: https://github.com/imath/wp-statuses/releases/tag/1.2.5
