### ISSUE TITLE
New post statuses not updating category count

### ISSUE THREAD

**Issue by Venutius** [imath/wp-statuses#25]
I've created a number of new post statuses and all is working well with the exception of one area - wp categories - selecting one of my new post statuses and adding a category does not update the number of posts assigned to that category and the category widget will only show categories with posts of published post status. I'm struggling to find a filter that I can use to correct this behaviour. I don't suppose you would have any suggestions?

**Comment by imath** [comment]
I think only 'public' statuses are taking in account for the category counts.
