### ISSUE TITLE
Some guys with hard hats use WordPress 4.9

### ISSUE THREAD

**Issue by szepeviktor** [imath/wp-statuses#34]
Could you give us your advise to make your plugins work with 4.9 core?
Anything goes!

**Comment by imath** [comment]
Hi,

Have you try to use a previous version ?

This one https://github.com/imath/wp-statuses/releases/tag/1.2.5 is compatible up to WordPress 4.7.

**Comment by szepeviktor** [comment]
Thank you for the idea.

What could halt execution of v2 version on WordPress 4.9?

**Comment by imath** [comment]
The block editor might not be there. You don’t need v2 if you’re not using WordPress 5.0 or up.

imath
https://imathi.eu
________________________________
De : Viktor Szépe <notifications@github.com>
Envoyé : Friday, September 6, 2019 5:01:07 PM
À : imath/wp-statuses <wp-statuses@noreply.github.com>
Cc : imath <imathi.eu@outlook.fr>; Comment <comment@noreply.github.com>
Objet : Re: [imath/wp-statuses] Some guys with hard hats use WordPress 4.9 (#34)


Thank you for the idea.

What could halt execution of v2 version on WordPress 4.9?

**Comment by szepeviktor** [comment]
Thank you!!
