### ISSUE TITLE
Admin can not view post if "public" set to false.

### ISSUE THREAD

**Issue by gangesh** [imath/wp-statuses#37]
Hello,
As in example below, setting "Public" to false, post disappears from admin post list, and can not be previewed either by users with Administrator level. 

How can a status behave like a "Pending" status?

```
function example_register()
{
    register_post_status('assigned', array(
        'label' => _x('Assigned', 'post status label', 'plugin-domain'),
        'public' => false,
        'label_count' => _n_noop('Assigned <span class="count">(%s)</span>', 'Assigned <span class="count">(%s)</span>', 'plugin-domain'),
        'post_type' => array('product'), // Define one or more post types the status can be applied to.
        'show_in_admin_all_list' => true,
        'show_in_admin_status_list' => true,
        'show_in_metabox_dropdown' => true,
        'show_in_inline_dropdown' => true,
        'dashicon' => 'dashicons-businessman',
    ));
}
```

Thanks in advance.

**Comment by imath** [comment]
Hi,

The plugin doesn’t change anything about how the Status API works in WordPress, it just makes it possible to choose the custom status from the WordPress UI and to only apply custom status to given post types. If you need to mimic the pending status you can probably try to use the same way this status is registered by WordPress.

imath
https://imathi.eu
________________________________
De : Gangesh Matta <notifications@github.com>
Envoyé : Monday, December 2, 2019 12:52:48 PM
À : imath/wp-statuses <wp-statuses@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [imath/wp-statuses] Admin can not view post if "public" set to false. (#37)


Hello,
As in example below, setting "Public" to false, post disappears from admin post list, and can not be previewed either by users with Administrator level.

How can a status behave like a "Pending" status?

function example_register()
{
    register_post_status('assigned', array(
        'label' => _x('Assigned', 'post status label', 'plugin-domain'),
        'public' => false,
        'label_count' => _n_noop('Assigned <span class="count">(%s)</span>', 'Assigned <span class="count">(%s)</span>', 'plugin-domain'),
        'post_type' => array('product'), // Define one or more post types the status can be applied to.
        'show_in_admin_all_list' => true,
        'show_in_admin_status_list' => true,
        'show_in_metabox_dropdown' => true,
        'show_in_inline_dropdown' => true,
        'dashicon' => 'dashicons-businessman',
    ));
}


Thanks in advance.
