### ISSUE TITLE
Post revisions not showing up when the plugin is active?

### ISSUE THREAD

**Issue by pdobrescu** [imath/wp-statuses#39]
Hello and thanks for this plugin!

We're using this plugin on a site for quite a long time and we recently realized that the Post Revisions section of the `Publishing` block in the post editor is gone (when trying to restore an older version of a page). Here's how it looks now (in Classic Editor):

![image](https://user-images.githubusercontent.com/1044106/78568756-f38e3780-77f8-11ea-8712-7d0f89631943.png)

And here's how it looks with the WP Statuses plugin deactivated:

![image](https://user-images.githubusercontent.com/1044106/78568806-056fda80-77f9-11ea-96f5-6d43be9be95f.png)

Is this supposed to happen? Is there maybe a setting for this that I overlooked?

Thank you!

**Comment by imath** [comment]
Thanks for your report. Good catch. I'm going to fix this asap.
