### ISSUE TITLE
Add post visibility for logged in users

### ISSUE THREAD

**Issue by aleafa** [imath/wp-statuses#4]
It seems custom statuses are not able to emulate the visibility settings of the built-in `draft` and `pending` post status types. It would be helpful to be able to display a status type only when logged in – or am I missing an option that's already present?

**Comment by lajala** [comment]
Right. In my case, I want users to be able to interact with posts throughout an editorial process (example flow: `submitted`, `assigned`, `reviewed`, `resubmitted`, `publish`). Only published posts should be visible to users who are not logged in. Does that make sense? I think this feature would just require a parameter passed to a query filter function. What do you think?

**Comment by imath** [comment]
i think you should keep the draft & pending statuses and use JavasSript to rename them the way you want because the plugin is not supporting the preview behavior these two kinds of specific statuses are generating.

imath.
http://profiles.wordpress.org/imath/
