### ISSUE TITLE
Post status don't show up for editors

### ISSUE THREAD

**Issue by msaari** [imath/wp-statuses#42]
Everything works well for a user with an Admin role. An user with an Editor role, only "Draft" and "Pending Review" appear in the dropdown in the Block editor.

The REST API returns correct post types, but the dropdown doesn't show them. The problem is `hasPublishAction`: it's `false` in all cases for an Editor user. Editor should have permissions to publish posts, though, so that's for some reason incorrect.

I'm using the latest version of WP-Statuses fresh from GitHub and Gutenberg that's bundled with WP 5.4.1 (using Gutenberg 8.1.0 doesn't help).

**Comment by imath** [comment]
Hi @msaari 

Thanks a lot for reporting this issue. I'm looking at it right now.

**Comment by imath** [comment]
I've just tested as an Editor. And it works as expected for me. I've tested with the same configuration as yours. Here's a screenshot:

![Capture d’écran 2020-05-30 à 11 49 24](https://user-images.githubusercontent.com/1834524/83325323-ccd60580-a26b-11ea-83e5-f4fd0cd8a594.png)

**Comment by msaari** [comment]
Weird, I can get this to work on a clean site, but not on the dev version of my actual site – even if I disable all plugins except WP-Statuses and the plugin that creates my custom post status. On that site, only Draft and Pending Review appear for the editor user, no matter what I try. On another site, with the same theme and the same two plugins active, it works.

Well, more digging for me, it seems...

**Comment by imath** [comment]
Hi I've rechecked. It's working as expected. I suspect an issue with the way you set your custom post type capabilities.
