### ISSUE TITLE
How to add "Stick this post.." checkbox for CPT

### ISSUE THREAD

**Issue by xianx** [imath/wp-statuses#43]
How can I add "Stick this post.." checkbox for CPT on wp-statuses metabox?

**Comment by imath** [comment]
Using another plugin.

The sticky feature is only available for Posts in WordPress, WP Statuses is following this specification and only deals with Post statuses.

**Comment by xianx** [comment]
My question was how to hook into wp-statuses metabox "Stick this post.." checkbox for Custom Post Type. Your plugin wont allow other plugin to hook into. So I wanted to know how can I add "Stick this post.." checkbox for CPT on wp-statuses metabox?
