### ISSUE TITLE
Wordpress 5.5.1 Compatibility

### ISSUE THREAD

**Issue by andrefredette** [imath/wp-statuses#47]
Since updating to 5.5.1 we've discovered an issue where clicking "Publish" on a draft post will reload the page and display the "post published" message but the status remains as draft. Manually selecting "Publicly publish" from the dropdown removes the text from the publish button (https://share.getcloudapp.com/2NuyQGq9) but does work to publish the post.

There are also some javascript notices being reported when the status dropdown changes:
```
postL10n.saveDraft is deprecated since version 5.5.0! Use wp.i18n instead. common.min.js?ver=5.5.1:2 
postL10n.publishOnPast is deprecated since version 5.5.0! Use wp.i18n instead. common.min.js?ver=5.5.1:2 
postL10n.update is deprecated since version 5.5.0! Use wp.i18n instead. common.min.js?ver=5.5.1:2 
postL10n.dateFormat is deprecated since version 5.5.0! Use wp.i18n instead. common.min.js?ver=5.5.1:2 
```

**Comment by imath** [comment]
Thanks for your feedback, I'll look at it asap

**Comment by imath** [comment]
Hi @andrefredette I believe the PR #48 is fixing the issue. Could you test it?

**Comment by andrefredette** [comment]
@imath thank you, yes that PR does in fact correct the issue and restores normal behavior to the publish button.
