### ISSUE TITLE
Not wordpress 5.7 compatible

### ISSUE THREAD

**Issue by shawfactor** [imath/wp-statuses#51]

**Comment by shawfactor** [comment]
In wordpress 5.7 the function is_post_status_viewable has been added and is used in a number of places. Th problem is that $_builtin is a private variable in the WP_Statuses_Core_Status class. This creates fatal errors. I patched in by making $_builtin a public variable. I am nt sure that this is the best approacch but it works

**Comment by imath** [comment]
Thanks for your report, I'll give it a look asap.

**Comment by andronocean** [comment]
I made a pull request (#52) with @shawfactor's solution, if you want a quick fix. It's resolved the errors in my environments.
