### ISSUE TITLE
Uncaught Error: Cannot access private property WP_Statuses_Core_Status::$_builtin

### ISSUE THREAD

**Issue by toddlevy** [imath/wp-statuses#53]
The latest version of WordPress core (5.7) introduces an issue where private posts (or posts with a custom status that's not set to public) throw this error in admin and frontend...

`Uncaught Error: Cannot access private property WP_Statuses_Core_Status::$_builtin`

I tracked this down to the $_builtin property of the WP_Statuses_Core_Status within this plugin being private (while all the other properties are public).

**BEFORE**
`private $_builtin = false;`

**AFTER**
`public $_builtin = false;`

**Comment by imath** [comment]
Hi, you can update to master as this was fixed in the PR #52

**Comment by rodrigo-arias** [comment]
Hi @imath do you have plans to release a version patch that includes #52? I think the last 2.1.1 does not include it. Thanks

**Comment by imath** [comment]
Sure ! Thanks for reminding me about it. I’ll do it asap.

imath
https://imathi.eu
________________________________
De : Rodrigo Arias ***@***.***>
Envoyé : Wednesday, April 7, 2021 11:26:24 PM
À : imath/wp-statuses ***@***.***>
Cc : imath ***@***.***>; Mention ***@***.***>
Objet : Re: [imath/wp-statuses] Uncaught Error: Cannot access private property WP_Statuses_Core_Status::$_builtin (#53)


Hi @imath<https://github.com/imath> do you have plans to release a version patch that includes #52<https://github.com/imath/wp-statuses/pull/52>? I think the last 2.1.1 does not include it. Thanks

**Comment by claytoncollie** [comment]
@imath Hi there. Any chance we can get a release soon? Thanks for your hard work on this plugin!

**Comment by imath** [comment]
Hi @claytoncollie @rodrigo-arias & @toddlevy 

I've just released the 2.1.2 minor version, it's available here: https://github.com/imath/wp-statuses/releases/tag/2.1.2

Sorry for the delay and thanks for your patience.
