### ISSUE TITLE
Change default post status to Publish

### ISSUE THREAD

**Issue by claytoncollie** [imath/wp-statuses#55]
Hi. I am looking for a filter to change the default post status is `publish` instead of `draft`. After installing this plugin, my content editors are confused that when they write a post and hit the big blue button their post is not published. They have to toggle the post status and hit Update for it to be published. Is this possible to default to publish instead of draft?

**Comment by frafor1988** [comment]
Hi, same issue here!

**Comment by imath** [comment]
Ok, I've been looking at it. It's only happening when using the Block Editor. If you use the Classic one, you get the desired behavior.

The problem with the Block Editor is: it's not possible to extend the `PostPublishButton` component, see: https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-publish-button/index.js
