### ISSUE TITLE
attachment_submitbox_misc_actions missing?

### ISSUE THREAD

**Issue by toshotosho** [imath/wp-statuses#6]
You seem to be doing `post_submitbox_misc_actions` even when you're editing an attachment. 

Perhaps something like 
```
    if ('attachment' != $post->post_type) {
      do_action( 'post_submitbox_misc_actions', $post );
    }
    else {
      do_action( 'attachment_submitbox_misc_actions', $post );
    }

```
in /inc/admin/classes/class-wp-statuses-admin.php might work?

**Comment by imath** [comment]
Hi thanks for your feedback.

I haven't seen it as it relates to a screen you only reach when not using the Grid layout but using the List one.

There's no reason to register custom statuses for the attachment post type i think. So the UI shouldn't be changed for it. Working on it.
