### ISSUE TITLE
post_submitbox_start Action should include post object

### ISSUE THREAD

**Issue by shawfactor** [imath/wp-statuses#64]
The post_submitbox_start action called in 

wp-statuses/inc/admin/classes/class-wp-statuses-admin.php

should include the $post object as specified here:

https://developer.wordpress.org/reference/hooks/post_submitbox_start/

including this fix will improve compatibility with other plugins.

**Comment by imath** [comment]
Thanks for the report, I'll include it asap.

**Comment by shawfactor** [comment]
following up on this? Seems like a simple fix and I would like to keep my plugins in line with the official version of this library
