### ISSUE TITLE
The new GUI for Gutenberg is now confusing

### ISSUE THREAD

**Issue by shawfactor** [imath/wp-statuses#94]
Imath,

This is what I am seeing in teh block editor these days (latest version of wp-statuses library 2.1.8 library), there are no other active plugins. Obviously very confusing, as my custom post status is "archived" yet its shown as private in the other field. Is this the same issue as #74 or a new issue with a new block editor iteration?

![Screenshot from 2024-07-27 19-52-49](https://github.com/user-attachments/assets/60936b3f-cdc1-4844-a8f2-ff170019f251)

**Comment by imath** [comment]
I believe it was fixed by https://github.com/imath/wp-statuses/pull/92 Could you checkout master branch?

**Comment by shawfactor** [comment]
Imath this does not work at all in wordpress 6.6 (it did in 6.5), the above screenshot was in 6.6

I added this line and it it no longer confusing:

.editor-post-panel__row:has(.editor-post-status) { display: none	}

Can this be fixed in the next version of the library?

**Comment by imath** [comment]
Thanks for sharing your fix, I'll apply it asap 👌
